experiment: 
  type: experiment/online_learning
  runs: 1
  trials: 0
  steps: 0
  rate: 0
  test_interval: 20
  environment: 
    type: environment/leo_walk
    behavior: 
      type: behavior/leo_walk_sym
    xml: ../../leo/cfg/leo_walk.xml
    target_env: 
      type: environment/ode
      xml: ../../xml
      randomize: 1
      visualize: 1
    observe: torso_boom, hipright, hipleft, kneeright, kneeleft
    actuate: hipright, hipleft, kneeleft
  agent: 
    type: agent/zeromq
    communicator: 
      type: communicator/zeromq/request_reply
      pattern: ZMQ_SYNC_CLI
      cli: tcp://localhost:5555
    observation_dims: experiment/environment/observation_dims
    action_dims: experiment/environment/action_dims
    action_min: [  ]
    action_max: [  ]
    test: 0
  test_agent: 
    type: agent/zeromq
    communicator: 
      type: communicator/zeromq/request_reply
      pattern: ZMQ_SYNC_CLI
      cli: tcp://localhost:5555
    observation_dims: experiment/environment/observation_dims
    action_dims: experiment/environment/action_dims
    action_min: [  ]
    action_max: [  ]
    test: 1
  load_file: none
  save_every: test
